/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TripsStatus implements EnumType {

    CREATED("CREATED"),

    BOOKED("BOOKED"),

    RUNNING("RUNNING"),

    CANCELLED("CANCELLED");

    private final String literal;

    private TripsStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "trips_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
