/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.devp.trip.model.Keys;
import org.devp.trip.model.TripManagement;
import org.devp.trip.model.tables.records.TransportersRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transporters extends TableImpl<TransportersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>trip_management.transporters</code>
     */
    public static final Transporters TRANSPORTERS = new Transporters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransportersRecord> getRecordType() {
        return TransportersRecord.class;
    }

    /**
     * The column <code>trip_management.transporters.id</code>.
     */
    public final TableField<TransportersRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>trip_management.transporters.user_id</code>.
     */
    public final TableField<TransportersRecord, ULong> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>trip_management.transporters.name</code>.
     */
    public final TableField<TransportersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(191).nullable(false), this, "");

    /**
     * The column <code>trip_management.transporters.email</code>.
     */
    public final TableField<TransportersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(191).nullable(false), this, "");

    /**
     * The column <code>trip_management.transporters.address</code>.
     */
    public final TableField<TransportersRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>trip_management.transporters.phone</code>.
     */
    public final TableField<TransportersRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>trip_management.transporters.profile_image</code>.
     */
    public final TableField<TransportersRecord, String> PROFILE_IMAGE = createField(DSL.name("profile_image"), SQLDataType.VARCHAR(191), this, "");

    /**
     * The column <code>trip_management.transporters.status</code>. 0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED
     */
    public final TableField<TransportersRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED");

    /**
     * The column <code>trip_management.transporters.created_at</code>.
     */
    public final TableField<TransportersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>trip_management.transporters.updated_at</code>.
     */
    public final TableField<TransportersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private Transporters(Name alias, Table<TransportersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transporters(Name alias, Table<TransportersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>trip_management.transporters</code> table reference
     */
    public Transporters(String alias) {
        this(DSL.name(alias), TRANSPORTERS);
    }

    /**
     * Create an aliased <code>trip_management.transporters</code> table reference
     */
    public Transporters(Name alias) {
        this(alias, TRANSPORTERS);
    }

    /**
     * Create a <code>trip_management.transporters</code> table reference
     */
    public Transporters() {
        this(DSL.name("transporters"), null);
    }

    public <O extends Record> Transporters(Table<O> child, ForeignKey<O, TransportersRecord> key) {
        super(child, key, TRANSPORTERS);
    }

    @Override
    public Schema getSchema() {
        return TripManagement.TRIP_MANAGEMENT;
    }

    @Override
    public Identity<TransportersRecord, ULong> getIdentity() {
        return (Identity<TransportersRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransportersRecord> getPrimaryKey() {
        return Keys.KEY_TRANSPORTERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TransportersRecord>> getKeys() {
        return Arrays.<UniqueKey<TransportersRecord>>asList(Keys.KEY_TRANSPORTERS_PRIMARY);
    }

    @Override
    public Transporters as(String alias) {
        return new Transporters(DSL.name(alias), this);
    }

    @Override
    public Transporters as(Name alias) {
        return new Transporters(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transporters rename(String name) {
        return new Transporters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transporters rename(Name name) {
        return new Transporters(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
