/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model;


import org.devp.trip.model.tables.Users;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in trip_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_API_KEY_IDX = Internal.createIndex(DSL.name("api_key_idx"), Users.USERS, new OrderField[] { Users.USERS.API_KEY }, false);
}
