/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model;


import org.devp.trip.model.tables.Transporters;
import org.devp.trip.model.tables.TripTraceInfos;
import org.devp.trip.model.tables.Users;
import org.devp.trip.model.tables.records.TransportersRecord;
import org.devp.trip.model.tables.records.TripTraceInfosRecord;
import org.devp.trip.model.tables.records.UsersRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * trip_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TransportersRecord> KEY_TRANSPORTERS_PRIMARY = Internal.createUniqueKey(Transporters.TRANSPORTERS, DSL.name("KEY_transporters_PRIMARY"), new TableField[] { Transporters.TRANSPORTERS.ID }, true);
    public static final UniqueKey<TripTraceInfosRecord> KEY_TRIP_TRACE_INFOS_PRIMARY = Internal.createUniqueKey(TripTraceInfos.TRIP_TRACE_INFOS, DSL.name("KEY_trip_trace_infos_PRIMARY"), new TableField[] { TripTraceInfos.TRIP_TRACE_INFOS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
}
