/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model;


import org.devp.trip.model.tables.Transporters;
import org.devp.trip.model.tables.TripTraceInfos;
import org.devp.trip.model.tables.Trips;
import org.devp.trip.model.tables.Users;


/**
 * Convenience access to all tables in trip_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>trip_management.transporters</code>.
     */
    public static final Transporters TRANSPORTERS = Transporters.TRANSPORTERS;

    /**
     * The table <code>trip_management.trip_trace_infos</code>.
     */
    public static final TripTraceInfos TRIP_TRACE_INFOS = TripTraceInfos.TRIP_TRACE_INFOS;

    /**
     * The table <code>trip_management.trips</code>.
     */
    public static final Trips TRIPS = Trips.TRIPS;

    /**
     * The table <code>trip_management.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
