/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model;


import java.util.Arrays;
import java.util.List;

import org.devp.trip.model.tables.Transporters;
import org.devp.trip.model.tables.TripTraceInfos;
import org.devp.trip.model.tables.Trips;
import org.devp.trip.model.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripManagement extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>trip_management</code>
     */
    public static final TripManagement TRIP_MANAGEMENT = new TripManagement();

    /**
     * The table <code>trip_management.transporters</code>.
     */
    public final Transporters TRANSPORTERS = Transporters.TRANSPORTERS;

    /**
     * The table <code>trip_management.trip_trace_infos</code>.
     */
    public final TripTraceInfos TRIP_TRACE_INFOS = TripTraceInfos.TRIP_TRACE_INFOS;

    /**
     * The table <code>trip_management.trips</code>.
     */
    public final Trips TRIPS = Trips.TRIPS;

    /**
     * The table <code>trip_management.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private TripManagement() {
        super("trip_management", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Transporters.TRANSPORTERS,
            TripTraceInfos.TRIP_TRACE_INFOS,
            Trips.TRIPS,
            Users.USERS);
    }
}
