/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model.tables.records;


import java.time.LocalDateTime;

import org.devp.trip.model.tables.Transporters;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportersRecord extends UpdatableRecordImpl<TransportersRecord> implements Record10<ULong, ULong, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trip_management.transporters.id</code>.
     */
    public TransportersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>trip_management.transporters.user_id</code>.
     */
    public TransportersRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>trip_management.transporters.name</code>.
     */
    public TransportersRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trip_management.transporters.email</code>.
     */
    public TransportersRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trip_management.transporters.address</code>.
     */
    public TransportersRecord setAddress(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trip_management.transporters.phone</code>.
     */
    public TransportersRecord setPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.phone</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trip_management.transporters.profile_image</code>.
     */
    public TransportersRecord setProfileImage(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.profile_image</code>.
     */
    public String getProfileImage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>trip_management.transporters.status</code>. 0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED
     */
    public TransportersRecord setStatus(Byte value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.status</code>. 0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>trip_management.transporters.created_at</code>.
     */
    public TransportersRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>trip_management.transporters.updated_at</code>.
     */
    public TransportersRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.transporters.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<ULong, ULong, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Transporters.TRANSPORTERS.ID;
    }

    @Override
    public Field<ULong> field2() {
        return Transporters.TRANSPORTERS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Transporters.TRANSPORTERS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Transporters.TRANSPORTERS.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Transporters.TRANSPORTERS.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Transporters.TRANSPORTERS.PHONE;
    }

    @Override
    public Field<String> field7() {
        return Transporters.TRANSPORTERS.PROFILE_IMAGE;
    }

    @Override
    public Field<Byte> field8() {
        return Transporters.TRANSPORTERS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Transporters.TRANSPORTERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Transporters.TRANSPORTERS.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getPhone();
    }

    @Override
    public String component7() {
        return getProfileImage();
    }

    @Override
    public Byte component8() {
        return getStatus();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getPhone();
    }

    @Override
    public String value7() {
        return getProfileImage();
    }

    @Override
    public Byte value8() {
        return getStatus();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    @Override
    public TransportersRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public TransportersRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public TransportersRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TransportersRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TransportersRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public TransportersRecord value6(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public TransportersRecord value7(String value) {
        setProfileImage(value);
        return this;
    }

    @Override
    public TransportersRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public TransportersRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TransportersRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TransportersRecord values(ULong value1, ULong value2, String value3, String value4, String value5, String value6, String value7, Byte value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransportersRecord
     */
    public TransportersRecord() {
        super(Transporters.TRANSPORTERS);
    }

    /**
     * Create a detached, initialised TransportersRecord
     */
    public TransportersRecord(ULong id, ULong userId, String name, String email, String address, String phone, String profileImage, Byte status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Transporters.TRANSPORTERS);

        setId(id);
        setUserId(userId);
        setName(name);
        setEmail(email);
        setAddress(address);
        setPhone(phone);
        setProfileImage(profileImage);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
