/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model.tables.records;


import java.time.LocalDateTime;

import org.devp.trip.model.enums.TripsStatus;
import org.devp.trip.model.tables.Trips;
import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripsRecord extends TableRecordImpl<TripsRecord> implements Record11<ULong, ULong, String, String, String, LocalDateTime, LocalDateTime, TripsStatus, String, String, ULong> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trip_management.trips.user_id</code>.
     */
    public TripsRecord setUserId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>trip_management.trips.transporter_id</code>.
     */
    public TripsRecord setTransporterId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.transporter_id</code>.
     */
    public ULong getTransporterId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>trip_management.trips.pickup_location</code>.
     */
    public TripsRecord setPickupLocation(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.pickup_location</code>.
     */
    public String getPickupLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trip_management.trips.dropoff_location</code>.
     */
    public TripsRecord setDropoffLocation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.dropoff_location</code>.
     */
    public String getDropoffLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trip_management.trips.others_info</code>.
     */
    public TripsRecord setOthersInfo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.others_info</code>.
     */
    public String getOthersInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trip_management.trips.created_at</code>.
     */
    public TripsRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>trip_management.trips.updated_at</code>.
     */
    public TripsRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>trip_management.trips.status</code>.
     */
    public TripsRecord setStatus(TripsStatus value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.status</code>.
     */
    public TripsStatus getStatus() {
        return (TripsStatus) get(7);
    }

    /**
     * Setter for <code>trip_management.trips.pickup_lat_lng</code>.
     */
    public TripsRecord setPickupLatLng(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.pickup_lat_lng</code>.
     */
    public String getPickupLatLng() {
        return (String) get(8);
    }

    /**
     * Setter for <code>trip_management.trips.dropoff_lat_lng</code>.
     */
    public TripsRecord setDropoffLatLng(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.dropoff_lat_lng</code>.
     */
    public String getDropoffLatLng() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trip_management.trips.id</code>.
     */
    public TripsRecord setId(ULong value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.trips.id</code>.
     */
    public ULong getId() {
        return (ULong) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<ULong, ULong, String, String, String, LocalDateTime, LocalDateTime, TripsStatus, String, String, ULong> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<ULong, ULong, String, String, String, LocalDateTime, LocalDateTime, TripsStatus, String, String, ULong> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Trips.TRIPS.USER_ID;
    }

    @Override
    public Field<ULong> field2() {
        return Trips.TRIPS.TRANSPORTER_ID;
    }

    @Override
    public Field<String> field3() {
        return Trips.TRIPS.PICKUP_LOCATION;
    }

    @Override
    public Field<String> field4() {
        return Trips.TRIPS.DROPOFF_LOCATION;
    }

    @Override
    public Field<String> field5() {
        return Trips.TRIPS.OTHERS_INFO;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Trips.TRIPS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Trips.TRIPS.UPDATED_AT;
    }

    @Override
    public Field<TripsStatus> field8() {
        return Trips.TRIPS.STATUS;
    }

    @Override
    public Field<String> field9() {
        return Trips.TRIPS.PICKUP_LAT_LNG;
    }

    @Override
    public Field<String> field10() {
        return Trips.TRIPS.DROPOFF_LAT_LNG;
    }

    @Override
    public Field<ULong> field11() {
        return Trips.TRIPS.ID;
    }

    @Override
    public ULong component1() {
        return getUserId();
    }

    @Override
    public ULong component2() {
        return getTransporterId();
    }

    @Override
    public String component3() {
        return getPickupLocation();
    }

    @Override
    public String component4() {
        return getDropoffLocation();
    }

    @Override
    public String component5() {
        return getOthersInfo();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public TripsStatus component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getPickupLatLng();
    }

    @Override
    public String component10() {
        return getDropoffLatLng();
    }

    @Override
    public ULong component11() {
        return getId();
    }

    @Override
    public ULong value1() {
        return getUserId();
    }

    @Override
    public ULong value2() {
        return getTransporterId();
    }

    @Override
    public String value3() {
        return getPickupLocation();
    }

    @Override
    public String value4() {
        return getDropoffLocation();
    }

    @Override
    public String value5() {
        return getOthersInfo();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public TripsStatus value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getPickupLatLng();
    }

    @Override
    public String value10() {
        return getDropoffLatLng();
    }

    @Override
    public ULong value11() {
        return getId();
    }

    @Override
    public TripsRecord value1(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public TripsRecord value2(ULong value) {
        setTransporterId(value);
        return this;
    }

    @Override
    public TripsRecord value3(String value) {
        setPickupLocation(value);
        return this;
    }

    @Override
    public TripsRecord value4(String value) {
        setDropoffLocation(value);
        return this;
    }

    @Override
    public TripsRecord value5(String value) {
        setOthersInfo(value);
        return this;
    }

    @Override
    public TripsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TripsRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TripsRecord value8(TripsStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public TripsRecord value9(String value) {
        setPickupLatLng(value);
        return this;
    }

    @Override
    public TripsRecord value10(String value) {
        setDropoffLatLng(value);
        return this;
    }

    @Override
    public TripsRecord value11(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public TripsRecord values(ULong value1, ULong value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, TripsStatus value8, String value9, String value10, ULong value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TripsRecord
     */
    public TripsRecord() {
        super(Trips.TRIPS);
    }

    /**
     * Create a detached, initialised TripsRecord
     */
    public TripsRecord(ULong userId, ULong transporterId, String pickupLocation, String dropoffLocation, String othersInfo, LocalDateTime createdAt, LocalDateTime updatedAt, TripsStatus status, String pickupLatLng, String dropoffLatLng, ULong id) {
        super(Trips.TRIPS);

        setUserId(userId);
        setTransporterId(transporterId);
        setPickupLocation(pickupLocation);
        setDropoffLocation(dropoffLocation);
        setOthersInfo(othersInfo);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setStatus(status);
        setPickupLatLng(pickupLatLng);
        setDropoffLatLng(dropoffLatLng);
        setId(id);
    }
}
