/*
 * This file is generated by jOOQ.
 */
package org.devp.trip.model.tables.records;


import java.time.LocalDateTime;

import org.devp.trip.model.tables.Users;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record14<ULong, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trip_management.users.id</code>.
     */
    public UsersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>trip_management.users.user_name</code>.
     */
    public UsersRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trip_management.users.full_name</code>.
     */
    public UsersRecord setFullName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trip_management.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trip_management.users.address</code>.
     */
    public UsersRecord setAddress(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trip_management.users.password</code>.
     */
    public UsersRecord setPassword(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>trip_management.users.phone</code>.
     */
    public UsersRecord setPhone(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>trip_management.users.profile_image</code>.
     */
    public UsersRecord setProfileImage(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.profile_image</code>.
     */
    public String getProfileImage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>trip_management.users.url</code>.
     */
    public UsersRecord setUrl(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.url</code>.
     */
    public String getUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>trip_management.users.logo</code>.
     */
    public UsersRecord setLogo(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.logo</code>.
     */
    public String getLogo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>trip_management.users.status</code>. 0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED
     */
    public UsersRecord setStatus(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.status</code>. 0 = PENDING, 1 = ACTIVE, 2 = INACTIVE, 3 = CANCEL_ACCOUNT, 4 = DELETE_ACCOUNT, 5 = ARCHIVE, 6 = REMOVED
     */
    public Byte getStatus() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>trip_management.users.api_key</code>.
     */
    public UsersRecord setApiKey(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>trip_management.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>trip_management.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>trip_management.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<ULong, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<ULong, String, String, String, String, String, String, String, String, String, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.FULL_NAME;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.PHONE;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.PROFILE_IMAGE;
    }

    @Override
    public Field<String> field9() {
        return Users.USERS.URL;
    }

    @Override
    public Field<String> field10() {
        return Users.USERS.LOGO;
    }

    @Override
    public Field<Byte> field11() {
        return Users.USERS.STATUS;
    }

    @Override
    public Field<String> field12() {
        return Users.USERS.API_KEY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Users.USERS.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getFullName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getPassword();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public String component8() {
        return getProfileImage();
    }

    @Override
    public String component9() {
        return getUrl();
    }

    @Override
    public String component10() {
        return getLogo();
    }

    @Override
    public Byte component11() {
        return getStatus();
    }

    @Override
    public String component12() {
        return getApiKey();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getFullName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getPassword();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public String value8() {
        return getProfileImage();
    }

    @Override
    public String value9() {
        return getUrl();
    }

    @Override
    public String value10() {
        return getLogo();
    }

    @Override
    public Byte value11() {
        return getStatus();
    }

    @Override
    public String value12() {
        return getApiKey();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdatedAt();
    }

    @Override
    public UsersRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setProfileImage(value);
        return this;
    }

    @Override
    public UsersRecord value9(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public UsersRecord value10(String value) {
        setLogo(value);
        return this;
    }

    @Override
    public UsersRecord value11(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public UsersRecord value12(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public UsersRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value14(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UsersRecord values(ULong value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Byte value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ULong id, String userName, String fullName, String email, String address, String password, String phone, String profileImage, String url, String logo, Byte status, String apiKey, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Users.USERS);

        setId(id);
        setUserName(userName);
        setFullName(fullName);
        setEmail(email);
        setAddress(address);
        setPassword(password);
        setPhone(phone);
        setProfileImage(profileImage);
        setUrl(url);
        setLogo(logo);
        setStatus(status);
        setApiKey(apiKey);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
